<?php

namespace RleeCMS\ShopBundle\Repository;

/**
 * ShopByLookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShopByLookRepository extends \Doctrine\ORM\EntityRepository
{
}
