imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@UserBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: ru

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    cache:  false
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - '::Form/fields.html.twig'
    globals:
        shop: "@rlee_cms_shop.core"
        router: "@router"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: gmail
    encryption: ssl
    host: smtp.gmail.com
    port: 465
    auth_mode: login
    username: toolai.fashion@gmail.com
    password: toolai2015
    spool:     { type: memory }


fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: RleeCMS\UserBundle\Entity\User
    registration:
        form:
            type: RleeCMS\UserBundle\Form\RegistrationFormType
stof_doctrine_extensions:
    orm:
        default:
            tree: true
            translatable: true
            timestampable: true
            loggable: true
            sluggable: true

mopa_bootstrap:
    form:  # Adds twig form theme  support
        show_legend: false # default is true
        show_child_legend: false # default is true
        render_optional_text:  false
        render_required_asterisk:  true
        collection:
            widget_remove_btn:
                attr:
                    class:                btn btn-default
                label:                ''
                icon:                 'trash-o'
                icon_inverted:        ~
                wrapper_div:
                    class:            form-group
                horizontal_wrapper_div:
                    class:            col-sm-3 col-sm-offset-3
            widget_add_btn:
                attr:
                    class:                btn btn-default
                label:                ''
                icon:                 'plus-circle'
    menu: ~  # enables twig helpers for menu
    icons:
        icon_set: fontawesome4

white_october_breadcrumbs:
    separator:          ''
    separatorClass:     'separator'
    listId:             'breadcrumbs'
    listClass:          'breadcrumb'
    itemClass:          ''
    linkRel:            ''
    locale:             ~ # defaults to null, so the default locale is used
    translation_domain: ~ # defaults to null, so the default domain is used
    viewTemplate:       '::breadcrumbs.html.twig'

knp_menu:
    # use "twig: false" to disable the Twig extension and the TwigRenderer
    twig:
        template: knp_menu.html.twig
    #  if true, enables the helper for PHP templates
    templating: false
    # the renderer to use, list is also available by default
    default_renderer: twig

fm_elfinder:
    instances:
        default:
            locale: %locale% # defaults to current request locale
            editor: custom # other options are tinymce, tinymce4, fm_tinymce,  form, simple, custom
            editor_template: AdminCMSBundle::FileBrowser/elfinder.html.twig # default null
            relative_path: false
            #path_prefix: / # for setting custom assets path prefix, useful for non vhost configurations, i.e. http://127.0.0.1/mysite/
            #fullscreen: true|false # defaults true, applies to simple and ckeditor editors
            #theme: smoothness # jquery theme, default is 'smoothness'
            include_assets: true # disable if you want to handle loading of the javascript and css assets yourself
            #visible_mime_types: ['image/png', 'image/jpg', 'image/jpeg'] # only show these mime types, defaults to show all
            connector:
                debug: true # defaults to false
                roots:       # at least one root must be defined
                    uploads:
                        #show_hidden: true|false # defaults to false, hide files that
                        driver: LocalFileSystem
                        path: uploads
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                        upload_deny: ['all']
                        upload_max_size: 200M
                        #attributes: example of setting attributes permission
                        #    - { pattern: '/(.*?)/', read: true, write: false, locked: true }
ivory_ck_editor:
    default_config: default
    configs:
        default:
            filebrowserBrowseRoute: elfinder
            filebrowserBrowseRouteParameters: []