<?php

namespace RleeCMS\AdminBundle\Repository;

/**
 * EmailDbRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailDbRepository extends \Doctrine\ORM\EntityRepository
{
}
